Repository slack-samples/bolt-python-custom-step-template, pull requests merged in 2024-08, with the labels that each got.

#24 fix: include the function_executed event in subscribed bot events
  manifest.json
Labels: audit, bug, update

#25 chore: update project for app settings configuration first
  .flake8
  .github/dependabot.yml
  .github/workflows/black.yml
  .github/workflows/flake8.yml
  .github/workflows/lint.yml
  .gitignore
  README.md
  pyproject.toml
  requirements.txt
  slack.json
Labels: documentation, enhancement

#27 chore: update terminology
  README.md
  app.py
  manifest.json
  tests/test_app.py
Labels: update
